package sk.benko.appsresource.client.designer;

public enum Sections {NONE, APPLICATION, TEMPLATE, 
  TEMPLATEGROUP, TEMPLATEATTRIBUTE, TEMPLATERELATION, OBJECTTYPE, 
  OBJECTATTRIBUTE, OBJECTRELATION, VALUETYPE, UNIT}
